Init:	MOV 	SCON, #52H		;mode 2, SM2=0, REN=1
	ANL 	PCON, #7FH		;SMOD = 0
LOOP:	MOV	R0, #20H
	LJMP	INPUT
	LJMP	OUTPUT
	LJMP	LOOP

INPUT:	CJNE	R0, #26H, ABOVE26
	JNB	TI, $			;TX empty?
	CLR	TI
	MOV	SBUF, R0
	SETB	TB8
	JNB	RI, $
	CLR	RI
	MOV	@R0, SBUF		;get received byte
	INC	R0
	LJMP	INPUT
ABOVE26:RET

OUTPUT:	CJNE	R0, #2CH, ABOVE2C
	JNB	TI, $			;TX empty?
	CLR	TI
	MOV	SBUF, R0
	SETB	TB8
	JNB	TI, $			;TX empty?
	CLR	TI
	MOV	SBUF, @R0
	CLR	TB8
	INC	R0
	LJMP	OUTPUT
ABOVE2C:RET